<?php

$title = $this -> translate('Add new customer');
$this -> headTitle($title);

?>

<div class="panel panel-default">
    <div class="panel-body">
        <h1><?php echo $title ?></h1>
        <p><?php echo $this -> translate('Please, fill the next form.') ?></p>
        <hr>
        <?php
            $form -> setAttribute('action', $this -> url('customer', array('action' => 'add')));
            $form -> setAttribute('onsubmit', 'return customer_onsubmit();');
            $form -> setAttribute('novalidate', '');
            $form -> setAttribute('class', 'form-horizontal');
            $form -> prepare();
            
            echo $this -> form() -> openTag($form);
        ?>
        <!-- firstname -->
        <div id="firstname-group" class="form-group">
            <label for="firstname" class="control-label col-sm-2"><?php echo $this -> translate('First Name') ?></label>
            <div class="col-sm-5">
                <input type="text" name="firstname" class="form-control" value autofocus />
            </div>
            <span id="firstname-required" class="help-block"><?php echo $this -> translate('Field is required!') ?></span>
        </div>
        
        <!-- lastname -->
        <div id="lastname-group" class="form-group">
            <label for="lastname" class="control-label col-sm-2"><?php echo $this -> translate('Last Name') ?></label>
            <div class="col-sm-5">
                <input type="text" name="lastname" class="form-control" value />
            </div>
            <span id="lastname-required" class="help-block"><?php echo $this -> translate('Field is required!') ?></span>
        </div>
        
        <!-- phone -->
        <div id="phone-group" class="form-group">
            <label for="phone" class="control-label col-sm-2"><?php echo $this -> translate('Phone') ?></label>
            <div class="col-sm-3">
                <input type="text" name="phone" class="form-control col-sm-2" value placeholder="(123) 456 7899" maxlength="14" />
            </div>
            <span id="phone-required" class="help-block"><?php echo $this -> translate('Field is required!') ?></span>
            <span id="phone-invalid" class="help-block"><?php echo $this -> translate('Field is invalid!') ?></span>
        </div>
        
        <!-- address -->
        <div id="address-group" class="form-group">
            <label for="address" class="control-label col-sm-2"><?php echo $this -> translate('Address') ?></label>
            <div class="col-sm-5">
                <input type="text" name="address" class="form-control" value />
            </div>
        </div>
        
        <!-- city -->
        <div id="city-group" class="form-group">
            <label for="city" class="control-label col-sm-2"><?php echo $this -> translate('City') ?></label>
            <div class="col-sm-5">
                <input type="text" name="city" class="form-control" value />
            </div>
        </div>
        
        <!-- state -->
        <div id="state-group" class="form-group">
            <label for="state" class="control-label col-sm-2"><?php echo $this -> translate ('State') ?></label>
            <div class="col-sm-5">
                <input type="text" name="state" class="form-control" value />
            </div>
            <span id="state-required" class="help-block"><?php echo $this -> translate('Field is required!') ?></span>
        </div>
        
        <!-- zipcode -->
        <div id="zipcode-group" class="form-group">
            <label for="zipcode" class="control-label col-sm-2"><?php echo $this -> translate('Zip Code') ?></label>
            <div class="col-sm-3">
                <input type="text" name="zipcode" class="form-control" value maxlength="5" />
            </div>
            <span id="zipcode-required" class="help-block"><?php echo $this -> translate('Field is required!') ?></span>
        </div>
        
        <!-- submit -->
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary"><?php echo $this -> translate('Add Customer') ?></button>
                <a href="<?php echo $this -> url('customer', array('action', 'index')) ?>" class="btn btn-danger"><?php echo $this -> translate('Cancel') ?></a>
            </div>
        </div>
        <?php
            echo $this -> form() -> closeTag();
        ?>
    </div>
</div>

<script src="<?php echo $this -> basePath('app/customer-validations.js') ?>"></script>