<?php

$title = "Delete customer";
$this -> headTitle($title);

?>

<div class="panel panel-default">
    <div class="panel-body">
        <h1>Detele customer</h1>
        <?php
            $url =  $this->url('customer', array(
                'action' => 'delete',
                'id'     => $this -> id,
            ));
        ?>
        <form action="<?php echo $url ?>" method="post" class="form-horizontal">
            <p>Are you sure?</p>
            <div class="btn-group">
                <button class="btn btn-success" name="del" value="Yes">Yes</button>
                <button class="btn btn-danger" name="del" value="No">No</button>
            </div>
            <hr>
            <!-- idcustomer -->
            <div class="form-group">
                <label for="idcustomer" class="control-label col-sm-2">Id</label>
                <div class="col-sm-5">
                    <input type="text" name="idcustomer" class="form-control" value="<?php echo $id ?>" disabled />
                </div>
            </div>
            
            <!-- firstname -->
            <div class="form-group">
                <label for="firstname" class="control-label col-sm-2">First Name</label>
                <div class="col-sm-5">
                    <input type="text" name="firstname" class="form-control" autofocus required value="<?php echo $customer -> firstname ?>" disabled />
                </div>
            </div>
            
            <!-- lastname -->
            <div class="form-group">
                <label for="lastname" class="control-label col-sm-2">Last Name</label>
                <div class="col-sm-5">
                    <input type="text" name="lastname" class="form-control" required value="<?php echo $customer -> lastname ?>" disabled />
                </div>
            </div>
            
            <!-- phone -->
            <div class="form-group">
                <label for="phone" class="control-label col-sm-2">Phone</label>
                <div class="col-sm-3">
                    <input type="text" name="phone" class="form-control col-sm-2" required value="<?php echo $customer -> phone ?>" disabled />
                </div>
            </div>
            
            <!-- address -->
            <div class="form-group">
                <label for="address" class="control-label col-sm-2">Address</label>
                <div class="col-sm-5">
                    <input type="text" name="address" class="form-control" value="<?php echo $customer -> address ?>" disabled />
                </div>
            </div>
            
            <!-- city -->
            <div class="form-group">
                <label for="city" class="control-label col-sm-2">City</label>
                <div class="col-sm-5">
                    <input type="text" name="city" class="form-control" value="<?php echo $customer -> city ?>" disabled />
                </div>
            </div>
            
            <!-- state -->
            <div class="form-group">
                <label for="state" class="control-label col-sm-2">State</label>
                <div class="col-sm-5">
                    <input type="text" name="state" class="form-control" value="<?php echo $customer -> state ?>" disabled />
                </div>
            </div>
            
            <!-- zipcode -->
            <div class="form-group">
                <label for="zipcode" class="control-label col-sm-2">Zip Code</label>
                <div class="col-sm-5">
                    <input type="text" name="zipcode" class="form-control" value="<?php echo $customer -> zipcode ?>" disabled />
                </div>
            </div>
        </form>
    </div>
</div>