<?php

$title = $this -> translate("Customers");
$this -> headTitle($title);

?>

<div class="panel panel-default">
    <div class="panel-body">
        <h1><?php echo $title ?></h1>
        <p><?php echo $this -> translate('Manage the list of all client registered.') ?></p>
        <hr>
        <table class="table">
            <thead>
                <tr>
                    <th><?php echo $this -> translate('Id') ?></th>
                    <th><?php echo $this -> translate('First Name') ?></th>
                    <th><?php echo $this -> translate('Last Name') ?></th>
                    <th><?php echo $this -> translate('Phone') ?></th>
                    <th><?php echo $this -> translate('Address') ?></th>
                    <th><?php echo $this -> translate('City') ?></th>
                    <th><?php echo $this -> translate('State') ?></th>
                    <th><?php echo $this -> translate('Zip Code') ?></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($customers as $customer) : ?>
                <tr>
                    <td><?php echo $this -> escapeHtml($customer -> idcustomer) ?></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> firstname) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> lastname) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> phone) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> address) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> city) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> state) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> zipcode) ?></div></td>
                    <td>
                        <a href="<?php echo $this -> url('customer', array('action' => 'edit', 'id' => $customer -> idcustomer)) ?>">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this -> url('customer', array('action' => 'delete', 'id' => $customer -> idcustomer)) ?>">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <a class="btn btn-default" href="<?php echo $this -> url('customer', array('action' => 'add')) ?>">
            <span class="glyphicon glyphicon-plus"></span> <?php echo $this -> translate('Add new customer') ?>
        </a>
        <a class="btn btn-default" href="<?php echo $this -> url('home') ?>">
            <span class="glyphicon glyphicon-home"></span> <?php echo $this -> translate('Back to home page') ?>
        </a>
    </div>
</div>