<?php

$title = "Customers";
$this -> headTitle($title);

?>

<div class="panel panel-default">
    <div class="panel-body">
        <h1><?php echo sprintf($this->translate('Customers'), '<h1>', '</h1>') ?></h1>
        <p><?php echo sprintf($this->translate('Manage the list of all client registered.'), '<p>', '</p>') ?></p>
        <hr>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Zip Code</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($customers as $customer) : ?>
                <tr>
                    <td><?php echo $this -> escapeHtml($customer -> idcustomer) ?></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> firstname) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> lastname) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> phone) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> address) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> city) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> state) ?></div></td>
                    <td><div contenteditable="true"><?php echo $this -> escapeHtml($customer -> zipcode) ?></div></td>
                    <td>
                        <a href="<?php echo $this -> url('customer', array('action' => 'edit', 'id' => $customer -> idcustomer)) ?>">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this -> url('customer', array('action' => 'delete', 'id' => $customer -> idcustomer)) ?>">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="btn-group">
            <a class="btn btn-default" href="<?php echo $this -> url('customer', array('action' => 'add')) ?>">
                <span class="glyphicon glyphicon-plus"></span> Add new customer
            </a>
            <a class="btn btn-default" href="<?php echo $this -> url('home') ?>">
                <span class="glyphicon glyphicon-arrow-left"></span> Back to home page
            </a>
        </div>
    </div>
</div>