<?php

$title = $this -> translate('Search/filter a customer');
$this -> headTitle($title);

?>

<div class="panel panel-default">
    <div class="panel-body">
        <h1><?php echo $title ?></h1>
        <p><?php echo $this -> translate('You can indicate one or more search filter conditions.') ?></p>
        <?php
            $form -> setAttribute('action', $this -> url('customer', array('action' => 'search')));
            $form -> setAttribute('class', 'form-inline');
            $form -> prepare();
            
            echo $this -> form() -> openTag($form);
        ?>
        <!-- idcustomer -->
        <div class="form-group">
            <label for="idcustomer"><?php echo $this -> translate('Id') ?></label>
            <input type="text" name="idcustomer" class="form-control" autofocus maxlength="5" value="<?php echo $customer -> idcustomer ?>" />
        </div>
        
        <!-- firstname -->
        <div class="form-group">
            <label for="firstname"><?php echo $this -> translate('First Name') ?></label>
            <input type="text" name="firstname" class="form-control" value="<?php echo $customer -> firstname ?>" />
        </div>
        
        <!-- lastname -->
        <div class="form-group">
            <label for="lastname"><?php echo $this -> translate('Last Name') ?></label>
            <input type="text" name="lastname" class="form-control" value="<?php echo $customer -> lastname ?>" />
        </div>
        
        <!-- phone -->
        <div class="form-group">
            <label for="phone"><?php echo $this -> translate('Phone') ?></label>
            <input type="text" name="phone" class="form-control" placeholder="(123) 456 7899" value="<?php echo $customer -> phone ?>" />
        </div>
        
        <!-- address -->
        <div class="form-group">
            <label for="address"><?php echo $this -> translate('Address') ?></label>
            <input type="text" name="address" class="form-control" value="<?php echo $customer -> address ?>" />
        </div>
        
        <!-- city -->
        <div class="form-group">
            <label for="city"><?php echo $this -> translate('City') ?></label>
            <input type="text" name="city" class="form-control" value="<?php echo $customer -> city ?>" />
        </div>
        
        <!-- state -->
        <div class="form-group">
            <label for="state"><?php echo $this -> translate('State') ?></label>
            <input type="text" name="state" class="form-control" value="<?php echo $customer -> state ?>" />
        </div>
        
        <!-- zipcode -->
        <div class="form-group">
            <label for="zipcode"><?php echo $this -> translate('Zip Code') ?></label>
            <input type="text" name="zipcode" class="form-control" maxlength="5" value="<?php echo $customer -> zipcode ?>" />
        </div>
        
        <!-- submit -->
        <br><br>
        <div class="form-group">
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span> <?php echo $this -> translate('Search') ?>
        </button>
        <a class="btn btn-default" href="<?php echo $this -> url('home') ?>">
            <span class="glyphicon glyphicon-home"></span> <?php echo $this -> translate('Back to home page') ?>
        </a>
        </div>
        <?php
            echo $this -> form() -> closeTag();
        ?>
        <hr>
        <table class="table">
            <thead>
                <tr>
                    <th><?php echo $this -> translate('Id') ?></th>
                    <th><?php echo $this -> translate('First Name') ?></th>
                    <th><?php echo $this -> translate('Last Name') ?></th>
                    <th><?php echo $this -> translate('Phone') ?></th>
                    <th><?php echo $this -> translate('Address') ?></th>
                    <th><?php echo $this -> translate('City') ?></th>
                    <th><?php echo $this -> translate('State') ?></th>
                    <th><?php echo $this -> translate('Zip Code') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                    $rows = count($this -> customers); 
                    if ($rows > 0) :
                        foreach ($customers as $customer) :
                ?>
                <tr>
                    <td><?php echo $this -> escapeHtml($customer -> idcustomer) ?></td>
                    <td><div><?php echo $this -> escapeHtml($customer -> firstname) ?></div></td>
                    <td><div><?php echo $this -> escapeHtml($customer -> lastname) ?></div></td>
                    <td><div><?php echo $this -> escapeHtml($customer -> phone) ?></div></td>
                    <td><div><?php echo $this -> escapeHtml($customer -> address) ?></div></td>
                    <td><div><?php echo $this -> escapeHtml($customer -> city) ?></div></td>
                    <td><div><?php echo $this -> escapeHtml($customer -> state) ?></div></td>
                    <td><div><?php echo $this -> escapeHtml($customer -> zipcode) ?></div></td>
                </tr>
                <?php
                        endforeach;
                    endif;
                ?>
                <tr>
                    <td colspan="8" style="text-align: center;"><small><?php echo $rows ?> custom(s) found.</small></td>
                </tr> 
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("input[name=idcustomer]").ForceNumericOnly();
        $("input[name=zipcode]").ForceNumericOnly();
    });
</script>