<?php

$title = $this -> translate('Home Page');
$this -> headTitle($title);

?>

<div class="panel panel-default">
    <div class="panel-body">
        <h1><?php echo $this -> translate('Welcome to home page') ?></h1>
        <hr>
        <p><?php echo $this -> translate('What can I do for you?') ?></p>
        <ul>
            <li>
                <a href="<?php echo $this -> url('customer', array('action' => 'index')) ?>">
                    <?php echo $this -> translate('Show the list of all registered customers.') ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this -> url('customer', array('action' => 'add')) ?>">
                    <?php echo $this -> translate('Add a new customer.') ?>
                </a>
            </li>
            <li>
                <a href="#">
                    <?php echo $this -> translate('Search/filter a customer.') ?>
                </a>
            </li>
            <li>
                <a href="#">
                    <?php echo $this -> translate('See README file.') ?>
                </a>
            </li>
        </ul>
    </div>
</div>